#!/usr/bin/env python3
"""One-time generator: emits src/font_latin1.h, src/font_cp850.h,
src/font_special_graphics.h as C byte arrays, sourced from GNU Unifont
(narrow 8x16 glyphs) and glibc's IBM850 charmap for the CP850 byte->
Unicode mapping. Not part of the RunVT build -- run once, commit output.
"""
import gzip
import re
import sys

UNIFONT_HEX = "/usr/share/unifont/unifont.hex"
IBM850_CHARMAP = "/usr/share/i18n/charmaps/IBM850.gz"

def load_unifont():
    glyphs = {}
    with open(UNIFONT_HEX, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or ":" not in line:
                continue
            cp_hex, data = line.split(":", 1)
            if len(data) != 32:
                continue  # skip wide (16px) glyphs, we only want narrow 8px
            cp = int(cp_hex, 16)
            glyphs[cp] = bytes.fromhex(data)
    return glyphs

def load_ibm850_map():
    # returns dict: byte value (0-255) -> unicode codepoint
    m = {}
    pat = re.compile(r"<U([0-9A-Fa-f]+)>\s+/x([0-9A-Fa-f]{2})\b")
    with gzip.open(IBM850_CHARMAP, "rt", encoding="utf-8", errors="replace") as f:
        for line in f:
            mo = pat.match(line)
            if mo:
                cp = int(mo.group(1), 16)
                byte = int(mo.group(2), 16)
                m[byte] = cp
    return m

BLANK = bytes(16)

def emit_table(fh, name, rows):
    fh.write("static const unsigned char %s[256][16] = {\n" % name)
    for i in range(256):
        b = rows.get(i, BLANK)
        hexbytes = ",".join("0x%02X" % x for x in b)
        fh.write("    { %s }, /* 0x%02X */\n" % (hexbytes, i))
    fh.write("};\n")

def main():
    uni = load_unifont()
    missing = []

    # --- Latin-1 / DEC Multinational: byte N -> Unicode codepoint N ---
    latin1_rows = {}
    for i in range(0x20, 0x100):
        if i in (0x7F,) or (0x80 <= i <= 0x9F):
            continue  # C1 control range, leave blank
        g = uni.get(i)
        if g is None:
            missing.append(("latin1", i))
            continue
        latin1_rows[i] = g

    # --- CP850: 0x00-0x7F identical to ASCII (reuse latin1 table's
    # low half), 0x80-0xFF via IBM850 charmap -> unicode -> unifont ---
    ibm850 = load_ibm850_map()
    cp850_rows = {}
    for i in range(0x20, 0x80):
        if i in latin1_rows:
            cp850_rows[i] = latin1_rows[i]
    for i in range(0x80, 0x100):
        cp = ibm850.get(i)
        if cp is None:
            missing.append(("cp850-map", i))
            continue
        g = uni.get(cp)
        if g is None:
            missing.append(("cp850-glyph", i))
            continue
        cp850_rows[i] = g

    # --- DEC Special Graphics: bytes 0x60-0x7E only ---
    # Standard VT100 mapping (DEC STD 070 / vt100.net), byte -> Unicode.
    dec_map = {
        0x60: 0x25C6,  # diamond
        0x61: 0x2592,  # checkerboard (medium shade)
        0x62: 0x2409,  # SYMBOL FOR HT
        0x63: 0x240C,  # SYMBOL FOR FF
        0x64: 0x240D,  # SYMBOL FOR CR
        0x65: 0x240A,  # SYMBOL FOR LF
        0x66: 0x00B0,  # degree
        0x67: 0x00B1,  # plus/minus
        0x68: 0x2424,  # SYMBOL FOR NL
        0x69: 0x240B,  # SYMBOL FOR VT
        0x6A: 0x2518,  # lower-right corner
        0x6B: 0x2510,  # upper-right corner
        0x6C: 0x250C,  # upper-left corner
        0x6D: 0x2514,  # lower-left corner
        0x6E: 0x253C,  # crossing lines
        0x6F: 0x23BA,  # scan line 1
        0x70: 0x23BB,  # scan line 3
        0x71: 0x2500,  # horizontal line (scan line 5)
        0x72: 0x23BC,  # scan line 7
        0x73: 0x23BD,  # scan line 9
        0x74: 0x251C,  # left tee
        0x75: 0x2524,  # right tee
        0x76: 0x2534,  # bottom tee
        0x77: 0x252C,  # top tee
        0x78: 0x2502,  # vertical line
        0x79: 0x2264,  # <=
        0x7A: 0x2265,  # >=
        0x7B: 0x03C0,  # pi
        0x7C: 0x2260,  # not equal
        0x7D: 0x00A3,  # UK pound
        0x7E: 0x00B7,  # middle dot
    }
    dec_rows = {}
    for byte, cp in dec_map.items():
        g = uni.get(cp)
        if g is None:
            missing.append(("special-graphics", byte, hex(cp)))
            continue
        dec_rows[byte] = g

    with open("src/font_latin1.h", "w") as fh:
        fh.write("/* Generated by tools/gen_fonts.py from GNU Unifont. Do not hand-edit. */\n")
        fh.write("#ifndef RUNVT_FONT_LATIN1_H\n#define RUNVT_FONT_LATIN1_H\n\n")
        emit_table(fh, "font_latin1", latin1_rows)
        fh.write("\n#endif\n")

    with open("src/font_cp850.h", "w") as fh:
        fh.write("/* Generated by tools/gen_fonts.py from GNU Unifont + glibc IBM850 charmap. Do not hand-edit. */\n")
        fh.write("#ifndef RUNVT_FONT_CP850_H\n#define RUNVT_FONT_CP850_H\n\n")
        emit_table(fh, "font_cp850", cp850_rows)
        fh.write("\n#endif\n")

    # --- reverse map for keyboard input encoding: Unicode -> CP850 byte,
    # covering the 0x80-0xFF range (0x00-0x7F is identity/ASCII) ---
    cp850_rev = []
    for byte, cp in sorted(ibm850.items()):
        if byte >= 0x80:
            cp850_rev.append((cp, byte))
    cp850_rev.sort()

    with open("src/cp850_encode.h", "w") as fh:
        fh.write("/* Generated by tools/gen_fonts.py from glibc's IBM850 charmap. Do not hand-edit. */\n")
        fh.write("#ifndef RUNVT_CP850_ENCODE_H\n#define RUNVT_CP850_ENCODE_H\n\n")
        fh.write("typedef struct { unsigned int cp; unsigned char byte; } CP850RevEntry;\n\n")
        fh.write("static const CP850RevEntry cp850_encode_table[%d] = {\n" % len(cp850_rev))
        for cp, byte in cp850_rev:
            fh.write("    { 0x%04X, 0x%02X },\n" % (cp, byte))
        fh.write("};\n\n")
        fh.write("static unsigned char cp850_encode(unsigned int codepoint) {\n")
        fh.write("    int lo = 0, hi = %d;\n" % (len(cp850_rev) - 1))
        fh.write("    while (lo <= hi) {\n")
        fh.write("        int mid = (lo + hi) / 2;\n")
        fh.write("        if (cp850_encode_table[mid].cp == codepoint) return cp850_encode_table[mid].byte;\n")
        fh.write("        if (cp850_encode_table[mid].cp < codepoint) lo = mid + 1; else hi = mid - 1;\n")
        fh.write("    }\n")
        fh.write("    return '?';\n")
        fh.write("}\n\n")
        fh.write("#endif\n")

    with open("src/font_special_graphics.h", "w") as fh:
        fh.write("/* Generated by tools/gen_fonts.py from GNU Unifont. Do not hand-edit. */\n")
        fh.write("/* Only bytes 0x60-0x7E are populated (DEC Special Graphics range); */\n")
        fh.write("/* all other entries are blank -- callers fall back to the normal font. */\n")
        fh.write("#ifndef RUNVT_FONT_SPECIAL_GRAPHICS_H\n#define RUNVT_FONT_SPECIAL_GRAPHICS_H\n\n")
        emit_table(fh, "font_special_graphics", dec_rows)
        fh.write("\n#endif\n")

    print("latin1 glyphs: %d/224 printable slots filled" % len(latin1_rows))
    print("cp850 glyphs: %d/224 printable slots filled" % len(cp850_rows))
    print("special graphics glyphs: %d/31 filled" % len(dec_rows))
    if missing:
        print("MISSING (%d):" % len(missing), file=sys.stderr)
        for m in missing:
            print("  ", m, file=sys.stderr)

if __name__ == "__main__":
    main()
